apiVersion: v1
kind: Namespace
metadata:
  name: voting
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-config
  namespace: voting
data:
  option-a: Cats
  option-b: Dogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote:before
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 2
            memory: 500Mi
        env:
          - name: OPTION_A
            valueFrom:
              configMapKeyRef:
                key: option-a
                name: vote-config
          - name: OPTION_B
            valueFrom:
              configMapKeyRef:
                key: option-b
                name: vote-config
        ports:
          - name: web
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
  - port: 80
    name: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vote
  namespace: voting
spec:
  rules:
    - host: vote-192-168-99-130.nip.io
      http:
        paths:
          - backend:
              serviceName: vote
              servicePort: 80

