apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: voting
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: result
  namespace: voting
spec:
  rules:
    - host: result-192-168-99-130.nip.io
      http:
        paths:
          - backend:
              serviceName: result
              servicePort: 80
