apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: rolling-updates
  labels:
    app: my-app
spec:
  replicas: 5
  strategy:
    type: RollingUpdate # or Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: demo
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
              name: web
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: /
