apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: rolling-updates
spec:
  rules:
    - host: XXX-XXX-XX-XXX.nip.io # insert "minikube ip"
      http:
        paths:
          - backend:
              serviceName: demo-app
              servicePort: 8080
