apiVersion: v1
kind: Pod
metadata:
  name: lobsters
  labels:
    app: lobsters
spec:
  containers:
    - image: gcr.io/google-samples/lobsters:1.0
      name: lobsters
      ports:
        - containerPort: 3000
          name: web
