apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-ingress-v2
  namespace: rolling-updates
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    # Canary by header and/or header-value
    nginx.ingress.kubernetes.io/canary-by-header: "x-version"
    nginx.ingress.kubernetes.io/canary-by-header-value: "2"
    # Canary percentage
    #nginx.ingress.kubernetes.io/canary-weight: "25"
spec:
  ingressClassName: nginx
  rules:
      # Set correct hostname for managed training 
      # environments (rollingupdates.clusterxx.training.cloudpirates.io)
    - host: rollingupdates.127-0-0-1.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: demo-app-v2
                port:
                  name: web