apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: rolling-updates
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: harbor.cloudpirates.io/training/rollouts-demo:blue
          name: demo-app
          resources:
            limits: {}
          ports:
            - containerPort: 3000
              name: web
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            httpGet:
              port: 3000
              path: /readyz
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            httpGet:
              port: 3000
              path: /livez


# Revision 1       -> Revision 2       -> Revision 3 -> "Rollback"
#                     Revision 4       <-


# Version 1 (blue) -> Version 2 (green) -> Version 3 (black)