apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: rolling-updates
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: web
  selector:
    app: demo-app
  sessionAffinity: None
  type: ClusterIP
