apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.cloudpirates.io/kubernetes-examples.git
    path: 10_additionals/code-server
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
