apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    helm:
      values: |-
        fullnameOverride : sealed-secrets-controller
        resources:
          requests:
            cpu: 50m
            memory: 24Mi
          limits:
            cpu: 200m
            memory: 64Mi
        commandArgs:
          - "--update-status"
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true