apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: vote-app
  project: vote-app
  source:
    path: vote-frontend/base
    repoURL: https://gitlab.cloudpirates.io/training/demo-application/infrastructure/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
