apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-disruption
  namespace: pdb-examples
spec:
  selector:
    matchLabels:
      app: pod-disruption
  template:
    metadata:
      labels:
        app: pod-disruption
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            limits: {}

