# PodDisruptionBudget is an object to define the max disruption that can be
# caused to a collection of pods
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: max-unavailable
  namespace: pdb-examples
spec:
# An eviction is allowed if at least "minAvailable" pods selected by
# "selector" will still be available after the eviction, i.e. even in the
# absence of the evicted pod.  So for example you can prevent all voluntary
# evictions by specifying "100%".
  minAvailable: 1
  selector:
    matchLabels:
      app: pod-disruption