apiVersion: v1
kind: Secret
metadata:
  name: learning-registry
  namespace: code-server
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.cloudpirates.io": {
          "auth": "bGVhcm5pbmc6Z2xwYXQtYWZZbnk2UEQ3RHpnUll0SmlmU3c="
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: code-server
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/instance: code-server
type: Opaque
data:
  password: bGVhcm5LOFM= # learnK8S