apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-volume
  namespace: guestbook-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
