apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: config-example
type: Opaque
# You don´t need to manually encode base64 values before creating a 
# secret, just let the api server do the work for you.
stringData:
  username: wordpress
  password: mysecretpass
  # For simplicity you yan also place (technically non secret) variables thats belongs to
  # this secret (i.e. for a database: username, password, hostname, port)
  hostname: localhost
  port: "3306"