apiVersion: v1
kind: Secret
metadata:
  name: wordpressdb
  namespace: config-example
type: Opaque
# You don´t need to manually encode base64 values before creating a 
# secret, just let the api server do the work for you.
stringData:
  host: localhost
  port: "3306"
  username: wordpress
  password: mysecretpass
  dsn: mysql://user:pass@hostname:3006/dbname