apiVersion: v1
kind: Pod
metadata:
  name: cpu-node-limits
  namespace: resources
spec:
  containers:
    - name: cpu-node-limit
      image: nginx
      resources:
        requests:
          cpu: "100" # 100 cores (not millicores)
        limits:
          cpu: "100"
