apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting
  labels:
    apps: vote
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: vote-service
  selector:
    app: vote
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-config
  namespace: voting
data:
  option-a: Cats
  option-b: Dogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote:before
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 100Mi
          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef:
                  key: option-a
                  name: vote-config
            - name: OPTION_B
              valueFrom:
                configMapKeyRef:
                  key: option-a
                  name: vote-config
          ports:
            - containerPort: 80
              name: vote
