apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vhost-ingress
  namespace: ingress-example
  annotations:
    kubernetes.io/acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  defaultBackend:
    service:
      name: echoserver
      port:
        number: 8080
  rules:
    - host: kubernetes.local
  tls:
    - hosts:
      - kubernetes.local
      secretName: my-tls-key
