apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vhost-ingress
  namespace: ingress-example
spec:
  rules:
      # insert "minikube ip", nip.io dynamically resolves the a-record
    - host: XXX-XXX-XX-XXX.nip.io
      http:
        paths:
          - backend:
              serviceName: echoserver
              servicePort: 8080
