# DaemonSet - Ensures a copy of a Pod runs on all (or selected) nodes in the cluster.
# Automatically adds Pods to new nodes and removes them when nodes are deleted.
# Common use cases: log collectors, monitoring agents, cluster storage daemons, network plugins.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      name: prometheus-node-exporter
  template:
    metadata:
      labels:
        name: prometheus-node-exporter
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: prometheus-node-exporter
        image: prom/node-exporter:latest
        resources:
          limits: {}
