apiVersion: v1
kind: Pod
metadata:
  name: test-empty-dir
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      volumeMounts:
        - mountPath: /cache
          name: cache
    - image: k8s.gcr.io/test-webserver
      name: sidecar
      volumeMounts:
        - mountPath: /tmp/cache
          name: cache
  volumes:
    - name: cache
      emptyDir: {}
