apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  # List of initialization containers belonging to the pod. Init containers are
  # executed in order prior to containers being started.
  initContainers:
    - name: init
      image: busybox
      command:
        ["sh", "-c", 'echo "Init Start" && sleep 10 && echo "Init complete"']
  containers:
    - name: application
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
      resources:
        limits: {}
