# A ConfigMap is an API object used to store non-confidential data in key-value pairs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: config-example
data:
  # single values
  configKey: my-config-value
  foo: bar
  # boolean and integer values must be escaped
  errorReporting: "1"
  debug: "true"
  # multiline config examples
  config.php: |
    <?php
    $foo = 'bar';
    $test = 'Hallo';
  jsonConfig: |
    {
      "foo": "bar",
      "key": "value"
    }
  gameProperties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
