apiVersion: v1
kind: Pod
metadata:
  name: full-example
  namespace: resources
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          # Set memory requests equal to memory limits
          memory: 56Mi
          cpu: 10m
        # It is not recommended to set cpu limits to your pods
        # @see https://home.robusta.dev/blog/stop-using-cpu-limits
        # @see https://github.com/kubernetes/design-proposals-archive/blob/8da1442ea29adccea40693357d04727127e045ed/node/resource-qos.md#compressible-resource-guarantees 
        limits:
          memory: 56Mi
