apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    helm:
      values: |-
        apiService:
          insecureSkipTLSVerify: true
        args:
          - '--kubelet-insecure-tls'
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
