apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    helm:
      values: |
        fullnameOverride: metrics-server
        apiService:
          create: true
        args:
          - --kubelet-insecure-tls
          - --secure-port=8443
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 6.5.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
