apiVersion: v1
kind: Pod
metadata:
  name: memory-node-limits
  namespace: resources
spec:
  containers:
    - name: memory-node-limits
      image: nginx
      resources:
        requests:
          memory: 50Gi
        limits:
          memory: 100Gi
