apiVersion: v1
kind: Service
metadata:
  name: nodeport-my-nginx
  namespace: networking-example
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: my-nginx
