apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-minio
  namespace: observability
spec:
  ingressClassName: nginx
  rules:
    - host: minio.aks-infra.cloudpirates.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: thanos-minio
                port:
                  number: 9001
                  # you can also use port->number instead of (servicePort) name
                  # number: 8080
