apiVersion: v1
kind: Pod
metadata:
  name: single-value-test
  namespace: config-example
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: MY_ENV_VARIABLE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to MY_ENV_VARIABLE
              name: test-config
              # Specify the key associated with the value
              key: config-key
