apiVersion: v1
kind: Pod
metadata:
  name: all-values-test
  namespace: config-example
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      resources: {}
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
        - configMapRef:
            name: test-config
