apiVersion: v1
kind: Secret
metadata:
  name: manual-secret
  namespace: config-example
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: YWRtaW4tcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-encode-secret
  namespace: config-example
type: Opaque
stringData:
  username: admin
  password: myPassword
