apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgAjR2f1nn05arRbkhu1O+MJQTiHS8nvJaOeHU7s6Rss5Ul2hQhqjD3ODySivuNQYXT8ocTnC7hxKHKdUo7aiZH4Imj5tacjoKel4KSstrycRxzF+ap8is3iUOGI6fs3sjKHQEX8BkS30IN1avjKjhiPDxFOD0zsx4HwzEuSWM0Fgb9kRLsoXhIFI/+IV0XPyBXFrEtRDcy+MvqBvbXwrN8asoMtVoOnnF0eaWJb4WTpM+WiIOgjZgKC25g3m0q4sexwHcCsRgvvG/X/2N4pd1ME2gwc3y6Fd+4b5HrvoTMRtssCYH/utFI7CrPYDdwuNvflHu1bwNqctIAAfrvs5O3um0PERSPfy81AtXP4J4aHA5RxbYRwe7CYmyjA7tksaMMrnTSTLUP79+GHJmN81sf6DjoEOMc8A8GeGw7mp4p16dEXYILUzFcuTnP/Qydlh8N0+RqX9Et/jTZV2p+k/FrgJFFhlzr8/JiFTHIsKNkTq5+s8yO81KCFIiaRDBYne0yZFuVau3tmLxu0IV3bQvRKirfeIG0eVRTsvWMbYWxtzpTWD+s0T2rjgZTDMfWvEF9B7PrktQi+EJQ+U+A2cSp+F8Q5xjrsOYqflZ3PoKLFfTIi6tgakNH3m0WC6xip0EgrkGMtYVyr80SffBqFukDqd5ZsZwzNUSC2stZ0siCogyMwzQC2fdSMzCdFMjucXF/TZh8=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
